//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealerShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int appointment_id { get; set; }
        public int client_id { get; set; }
        public int employee_id { get; set; }
        public int car_id { get; set; }
        public System.DateTime appointment_date { get; set; }
        public string status { get; set; }
        public int status_id { get; set; }
    
        public virtual car car { get; set; }
        public virtual client client { get; set; }
        public virtual employee employee { get; set; }
        public virtual status status1 { get; set; }
    }
}
