//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealerShip
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarDealershipEntities : DbContext
    {
        public CarDealershipEntities()
            : base("name=CarDealershipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<car> cars { get; set; }
        public virtual DbSet<catalog> catalogs { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
