//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealerShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalog
    {
        public int catalog_id { get; set; }
        public int car_id { get; set; }
        public string description { get; set; }
        public string image_url { get; set; }
    
        public virtual car car { get; set; }
    }
}
