//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealerShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReview
    {
        public int ReviewID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> CarID { get; set; }
        public string ReviewText { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
    }
}
