//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealerShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int feedback_id { get; set; }
        public int client_id { get; set; }
        public string feedback_text { get; set; }
        public System.DateTime feedback_date { get; set; }
    
        public virtual client client { get; set; }
    }
}
