//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealerShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
