//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealerShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int sale_id { get; set; }
        public int client_id { get; set; }
        public int employee_id { get; set; }
        public System.DateTime sale_date { get; set; }
        public decimal sale_price { get; set; }
        public int sale_status_id { get; set; }
        public int car_id { get; set; }
    
        public virtual client client { get; set; }
        public virtual employee employee { get; set; }
        public virtual sale_statuses sale_statuses { get; set; }
    }
}
