//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealerShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_counts
    {
        public int sales_count_id { get; set; }
        public int employee_id { get; set; }
        public int Sales_count { get; set; }
        public decimal total_sales { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
